export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const DESTROY_SESSION = 'DESTROY SESSION';
export const STATUS_UPDATE = 'STATUS_UPDATE';

export const REPORT_UPDATE = 'REPORT_UPDATE';
export const PROBLEM_UPDATE= 'PROBLEM_UPDATE'
/**Profile Update**/
export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const APPLICATION_LIST_UPDATE = 'APPLICATION_LIST_UPDATE';
export const USER_LIST_UPDATE = 'USERS_LIST_UPDATE';
export const VACANCY_LIST_UPDATE = 'VACANCY_LIST_UPDATE';
export const INTERVIEW_LIST_UPDATE = 'INTERVIEW_LIST_UPDATE';